### ISSUE TITLE
建议ppt(x)增加一份pdf版本

### ISSUE THREAD

**Issue by Xeonacid** [hzwer/shareOI#2]
以便在GitHub上在线预览

**Comment by hzwer** [comment]
相当一部分 ppt 带有动画，无法正确转为 pdf 格式，可能需要逐个 check

**Comment by Xeonacid** [comment]
[DP入门_阮行止.pptx](https://github.com/hzwer/shareOI/blob/master/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92/DP%E5%85%A5%E9%97%A8_%E9%98%AE%E8%A1%8C%E6%AD%A2.pptx) 这个就是带有动画的，但是看起来转换后没什么问题？
[DP入门_阮行止.pdf](https://github.com/hzwer/shareOI/files/4115446/DP._.pdf)
（使用Office本身的另存为功能）

**Comment by meteorsh** [comment]
> 以便在GitHub上在线预览

请教一下，GitHub是可以在线浏览pdf吗

**Comment by hzwer** [comment]
我想了一下，虽然 pdf 容易预览，但是 ppt 格式容易编辑
所以目前并不打算提供全 pdf 版
